#!/usr/bin/ksh
#
#################################################
# settings
#################################################

# Runfile. Global output to COMSO-EU for Case 2 (SR)

#Folgende Änderungen wurden gegenüber ifs2eu gemacht:
# - Gebietsgrößen
# - Verzeichnisse und const-files
# - Integrationszeitraum
# - lsso=.FALSE.,
# - lprog_qrqs=.FALSE.,


#Define Label for queue
QLabel=gl2eu_c2_m

#Define directories
indir=/home/scratch/users/stephan.rasp/Case2_20090129/d0glout
outdir=/home/scratch/users/stephan.rasp/Case2_20090129/d1euin_medium
extdir=/home/scratch/users/stephan.rasp/Case2_20090129/d0glout

#Define time properties
date=2009012900
hstart=0; hstop=24; hincbound=6

#Define output-grid (rotated)
startlon=-25.0; startlat=-28.0; ie=401; je=897
pollat=35; pollon=170.0

#Define input grid
istartlon=-90; istartlat=20; iie=721; ije=281

#Define parallelization
NPX=4
NPY=4
NPIO=0

#Define executable
INTLMEXE=/home/opt/int2lm_131101_2.00/int2lmexe

#################################################
# script
#################################################

#Calculade Nodes
NP1=`expr $NPX \* $NPY`
NP=`expr $NP1 + $NPIO`
N1=`expr $NP + 15`
NODES=`expr $N1 \/ 16`

#Copy this runscript
cp $0 $outdir/.

#Change to working and output directory
cd $outdir
rm -f INPUT

#################################################
# INPUT-file
#################################################
cat > INPUT << end_input
&CONTRL
  ydate_ini='$date', ydate_bd='$date', hstart=$hstart, hstop=$hstop, 
  hincbound=$hincbound, linitial=.TRUE.,  lboundaries =.TRUE.,nprocx=$NPX, 
  nprocy=$NPY, nprocio=0, lreorder=.FALSE., yinput_model='IFS', 
  ltime_mean=.TRUE., lfilter_oro=.TRUE., eps_filter=0.1, ilow_pass_oro=1, 
  ilow_pass_xso=0, rxso_mask=0.0, lfilter_pp=.FALSE., lbalance_pp=.FALSE., 
  norder_filter=5, luvcor=.TRUE.,lmulti_layer_in=.FALSE., lmulti_layer_lm=.TRUE., 
  l_smi=.FALSE., lprog_qi=.FALSE., lprog_rho_snow=.FALSE., lprog_qr_qs=.FALSE.,
  lsso=.TRUE., lforest=.TRUE., lbdclim=.FALSE., lt_cl_corr=.TRUE., itype_ndvi=0, 
  idbg_level=100, lseaice=.FALSE., itype_albedo=1,
/
&GRID_IN
  startlat_in_tot = $istartlat, startlon_in_tot = $istartlon, dlat_in = 0.25, 
  dlon_in = 0.25, ie_in_tot = $iie, je_in_tot = $ije, ke_in_tot = 91, 
  pollat_in = 90.0, pollon_in = 180.0, pcontrol_fi=20000.0,
/
&LMGRID
  startlat_tot  = $startlat, startlon_tot  = $startlon, dlon=0.0625, dlat=0.0625,
  ielm_tot=$ie, jelm_tot=$je, kelm_tot=40, pollat = $pollat, pollon = $pollon,
  ivctype=2, vcflat=11430.0, irefatm=2,
  vcoord_d=22700.00,20800.00,19100.00,17550.00,16150.00,14900.00,13800.00,12785.00,11875.00,11020.00,
           10205.00, 9440.00, 8710.00, 8015.00, 7355.00, 6725.00, 6130.00, 5565.00, 5035.00, 4530.00,   
            4060.00, 3615.00, 3200.00, 2815.00, 2455.00, 2125.00, 1820.00, 1545.00, 1295.00, 1070.00,  
             870.00,  695.00,  542.00,  412.00,  303.00,  214.00,  143.00,   89.00,   49.00,   20.00,
               0.00
/
&DATABASE
/
&DATA
  ie_ext=961, je_ext=961, ylmext_lfn='extpar_eu.grb', ylmext_cat='$extdir', 
  yinext_lfn='ec_ext.g1', yinext_form_read='apix', yinext_cat='$indir', 
  yin_cat='$indir', ylmext_form_read='apix', yin_form_read='apix', 
  ylm_cat='$outdir', yinput_type='analysis', ylm_form_write='api1',
  nprocess_ini = 131, nprocess_bd = 132, nl_soil_in=2, nl_soil_lm=2,

/
&PRICTR
/
end_input

#################################################
# jobfile-file und execution
################################################
rm -f batchjob YU* OUTPUT INPUT_* l* cosmo.out

#batchjob-file generieren
echo "#$ -S /bin/ksh" >> batchjob
echo "#$ -cwd" >> batchjob
echo "#$ -N $QLabel" >> batchjob
echo "#$ -pe mpich $NP" >> batchjob
echo "#$ -V" >> batchjob
echo "#$ -j y" >> batchjob
echo "#$ -R y" >> batchjob
echo "#$ -q eight">>batchjob
echo "#$ -M s.rasp@physik.uni-muenchen.de" >> batchjob
echo "#$ -m e" >> batchjob
echo "#$ -o $outdir/cosmo.out" >> batchjob
echo /home/opt/openmpi-1.6.4/bin/mpirun -np $NP $INTLMEXE >> batchjob

echo "rm -f INPUT_* ">> batchjob

#execute
chmod u+x batchjob
qsub $outdir/batchjob
rm -f batchjob

# /home/opt/openmpi-1.6.4/bin/mpirun -np $NP $INTLMEXE
